# Azure ML v2 Pipeline: prepare_training_data → train_risk_scoring (DATA_LAKE_LAYOUT §2.4; Plan §874).
# Chains azml-job-prepare-training logic with train_risk_scoring. Submit from containers/ml-service/scripts:
#   az ml job create --file azml-pipeline-prepare-then-risk-scoring.yaml \
#     --set inputs.risk_evaluations.path=abfs://<container>@<account>.dfs.core.windows.net/<path-to-risk_evaluations> \
#     --set inputs.ml_outcomes.path=abfs://<container>@<account>.dfs.core.windows.net/<path-to-ml_outcomes> \
#     [--set inputs.model_name.value=risk-scoring-global] \
#     [--set inputs.industry_id.value=<id>] \
#     [--set inputs.deploy_flag.value=--deploy] \
#     [--set settings.default_compute=azureml:<compute>]
# Env AZURE_ML_SUBSCRIPTION_ID, AZURE_ML_RESOURCE_GROUP, AZURE_ML_WORKSPACE_NAME. For --deploy: DEPLOY_*.
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: prepare-then-risk-scoring
display_name: prepare-then-risk-scoring
settings:
  default_compute: azureml:cpu-cluster
inputs:
  risk_evaluations:
    type: uri_folder
    path: https://REPLACE_OR_SET_AT_SUBMIT
  ml_outcomes:
    type: uri_folder
    path: https://REPLACE_OR_SET_AT_SUBMIT
  model_name:
    value: risk-scoring-global
  industry_id:
    value: ""
  deploy_flag:
    value: ""

jobs:
  prepare_training_data:
    type: command
    code: .
    command: >
      python prepare_training_data.py
      --risk-evaluations-path ${{inputs.risk_evaluations}}
      --ml-outcomes-path ${{inputs.ml_outcomes}}
      --output-path ${{outputs.training_prep}}/prepared.parquet
      --model-id risk_scoring
    inputs:
      risk_evaluations: ${{parent.inputs.risk_evaluations}}
      ml_outcomes: ${{parent.inputs.ml_outcomes}}
    outputs:
      training_prep:
        type: uri_folder
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
      conda_file: conda-prepare-train.yaml

  train_risk_scoring:
    type: command
    code: .
    command: python train_risk_scoring.py --input-path ${{inputs.training_data}} --model-name ${{inputs.model_name}} --industry-id ${{inputs.industry_id}} ${{inputs.deploy_flag}}
    inputs:
      training_data: ${{parent.jobs.prepare_training_data.outputs.training_prep}}
      model_name: ${{parent.inputs.model_name}}
      industry_id: ${{parent.inputs.industry_id}}
      deploy_flag: ${{parent.inputs.deploy_flag}}
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
      conda_file: conda-risk-scoring-train.yaml
