# Conda env for Azure ML Job: train_prophet_forecast.py (Plan ยง5.6, ยง877; TRAINING_SCRIPTS_SPEC ยง3.5).
# Training needs pandas, pyarrow, prophet, joblib; register/deploy needs azure-ai-ml, azure-identity.
name: prophet-train
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12
  - numpy
  - pandas
  - pyarrow
  - pip
  - pip:
    - prophet
    - joblib
    - azure-ai-ml
    - azure-identity
