# Conda env for Azure ML Job: train_risk_scoring.py (Plan ยง5.6, ยง874; TRAINING_SCRIPTS_SPEC ยง3.1).
# Training needs pandas, pyarrow; register/deploy needs azure-ai-ml, azure-identity.
name: risk-scoring-train
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12
  - numpy
  - pandas
  - pyarrow
  - pip
  - pip:
    - xgboost
    - azure-ai-ml
    - azure-identity
