# Conda env for Azure ML Job: train_win_probability.py (Plan ยง5.6, ยง876; TRAINING_SCRIPTS_SPEC ยง3.2).
# Training needs pandas, pyarrow, scikit-learn, xgboost; register/deploy needs azure-ai-ml, azure-identity.
name: win-probability-train
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12
  - numpy
  - pandas
  - pyarrow
  - pip
  - pip:
    - scikit-learn
    - xgboost
    - azure-ai-ml
    - azure-identity
