/**
 * Platform shard type definitions (CRM + integration).
 * Single source of truth for all non-system shard types; used by bootstrap.
 * @module shard-manager/startup/shardTypeDefinitions
 */

export interface PlatformShardTypeDefinition {
  id: string;
  name: string;
  description: string;
  schema: Record<string, unknown>;
  schemaVersion: string;
  isSystem: false;
}

/**
 * CRM and integration shard types. System types (c_competitor, c_product, etc.) remain in bootstrapShardTypes.
 */
export const PLATFORM_SHARD_TYPE_DEFINITIONS: PlatformShardTypeDefinition[] = [
  {
    id: 'opportunity',
    name: 'Opportunity',
    description: 'Sales opportunity with ML fields and integration tracking',
    schemaVersion: '1.1',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        amount: { type: 'number' },
        currency: { type: 'string' },
        stage: { type: 'string' },
        probability: { type: 'number', minimum: 0, maximum: 100 },
        expectedRevenue: { type: 'number' },
        closeDate: { type: 'string', format: 'date-time' },
        createdDate: { type: 'string', format: 'date-time' },
        ownerId: { type: 'string' },
        accountId: { type: 'string' },
        daysInStage: { type: 'number' },
        daysSinceLastActivity: { type: 'number' },
        dealVelocity: { type: 'number' },
        competitorCount: { type: 'number' },
        stakeholderCount: { type: 'number' },
        documentCount: { type: 'number' },
        emailCount: { type: 'number' },
        meetingCount: { type: 'number' },
        callCount: { type: 'number' },
        integrationSource: { type: 'string' },
        externalId: { type: 'string' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
        syncStatus: { type: 'string' },
        lastActivityDate: { type: 'string', format: 'date-time' },
        industry: { type: 'string' },
        industryId: { type: 'string' },
        competitorIds: { type: 'array', items: { type: 'string' } },
        stageUpdatedAt: { type: 'string', format: 'date-time' },
        stageDates: { type: 'object' },
      },
    },
  },
  {
    id: 'account',
    name: 'Account',
    description: 'Account with integration tracking and ML fields',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        industry: { type: 'string' },
        industryId: { type: 'string' },
        revenue: { type: 'number' },
        employeeCount: { type: 'number' },
        website: { type: 'string' },
        type: { type: 'string' },
        ownerId: { type: 'string' },
        integrationSource: { type: 'string' },
        externalId: { type: 'string' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
        historicalWinRate: { type: 'number' },
        historicalDealCount: { type: 'number' },
        historicalRevenue: { type: 'number' },
      },
    },
  },
  {
    id: 'contact',
    name: 'Contact',
    description: 'Contact with integration tracking and engagement fields',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        firstName: { type: 'string' },
        lastName: { type: 'string' },
        email: { type: 'string' },
        phone: { type: 'string' },
        title: { type: 'string' },
        accountId: { type: 'string' },
        integrationSource: { type: 'string' },
        externalId: { type: 'string' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
        emailInteractionCount: { type: 'number' },
        meetingAttendanceCount: { type: 'number' },
        lastInteractionDate: { type: 'string', format: 'date-time' },
        isKeyStakeholder: { type: 'boolean' },
      },
    },
  },
  {
    id: 'lead',
    name: 'Lead',
    description: 'Lead with integration tracking',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        firstName: { type: 'string' },
        lastName: { type: 'string' },
        email: { type: 'string' },
        phone: { type: 'string' },
        company: { type: 'string' },
        title: { type: 'string' },
        status: { type: 'string' },
        integrationSource: { type: 'string' },
        externalId: { type: 'string' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
      },
    },
  },
  {
    id: 'document',
    name: 'Document',
    description: 'Document from integrations (Google Drive, SharePoint, etc.)',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        title: { type: 'string' },
        description: { type: 'string' },
        documentType: { type: 'string', enum: ['pdf', 'docx', 'xlsx', 'pptx', 'txt', 'html', 'image', 'other'] },
        mimeType: { type: 'string' },
        size: { type: 'number' },
        integrationSource: { type: 'string', enum: ['google_drive', 'sharepoint', 'dropbox', 'onedrive', 'box'] },
        externalId: { type: 'string' },
        externalUrl: { type: 'string' },
        sourcePath: { type: 'string' },
        parentFolderId: { type: 'string' },
        parentFolderName: { type: 'string' },
        blobStorageUrl: { type: 'string' },
        blobStorageContainer: { type: 'string' },
        blobStoragePath: { type: 'string' },
        extractedText: { type: 'string' },
        extractedTextLength: { type: 'number' },
        pageCount: { type: 'number' },
        wordCount: { type: 'number' },
        language: { type: 'string' },
        summary: { type: 'string' },
        keyTopics: { type: 'array', items: { type: 'string' } },
        keyPhrases: { type: 'array', items: { type: 'string' } },
        entities: { type: 'array' },
        sentiment: { type: 'object' },
        category: { type: 'string', enum: ['proposal', 'contract', 'presentation', 'report', 'email_attachment', 'other'] },
        confidenceLevel: { type: 'string', enum: ['public', 'internal', 'confidential', 'restricted'] },
        containsPII: { type: 'boolean' },
        linkedOpportunityIds: { type: 'array', items: { type: 'string' } },
        linkedAccountIds: { type: 'array', items: { type: 'string' } },
        linkedContactIds: { type: 'array', items: { type: 'string' } },
        autoLinkingConfidence: { type: 'object' },
        createdAt: { type: 'string', format: 'date-time' },
        modifiedAt: { type: 'string', format: 'date-time' },
        lastAccessedAt: { type: 'string', format: 'date-time' },
        createdBy: { type: 'string' },
        modifiedBy: { type: 'string' },
        ownerId: { type: 'string' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
        syncStatus: { type: 'string', enum: ['synced', 'pending', 'error'] },
        syncError: { type: 'string' },
        processingStatus: { type: 'string', enum: ['pending', 'processing', 'completed', 'failed'] },
        processingError: { type: 'string' },
        textExtractionCompleted: { type: 'boolean' },
        analysisCompleted: { type: 'boolean' },
        vectorizationCompleted: { type: 'boolean' },
      },
    },
  },
  {
    id: 'email',
    name: 'Email',
    description: 'Email from integrations (Gmail, Outlook)',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        subject: { type: 'string' },
        threadId: { type: 'string' },
        messageId: { type: 'string' },
        integrationSource: { type: 'string', enum: ['gmail', 'outlook', 'exchange'] },
        externalId: { type: 'string' },
        from: { type: 'object' },
        to: { type: 'array' },
        cc: { type: 'array' },
        bcc: { type: 'array' },
        bodyHtml: { type: 'string' },
        bodyPlainText: { type: 'string' },
        snippet: { type: 'string' },
        hasAttachments: { type: 'boolean' },
        attachmentCount: { type: 'number' },
        attachments: { type: 'array' },
        isRead: { type: 'boolean' },
        isImportant: { type: 'boolean' },
        isFlagged: { type: 'boolean' },
        isReply: { type: 'boolean' },
        inReplyTo: { type: 'string' },
        labels: { type: 'array', items: { type: 'string' } },
        categories: { type: 'array', items: { type: 'string' } },
        sentiment: { type: 'object' },
        topics: { type: 'array', items: { type: 'string' } },
        keyPhrases: { type: 'array', items: { type: 'string' } },
        actionItems: { type: 'array' },
        containsPII: { type: 'boolean' },
        emailType: { type: 'string', enum: ['intro', 'proposal', 'negotiation', 'follow_up', 'internal', 'other'] },
        importance: { type: 'string', enum: ['low', 'normal', 'high'] },
        linkedOpportunityIds: { type: 'array', items: { type: 'string' } },
        linkedAccountIds: { type: 'array', items: { type: 'string' } },
        linkedContactIds: { type: 'array', items: { type: 'string' } },
        autoLinkingConfidence: { type: 'object' },
        sentAt: { type: 'string', format: 'date-time' },
        receivedAt: { type: 'string', format: 'date-time' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
        syncStatus: { type: 'string', enum: ['synced', 'pending', 'error'] },
        processingStatus: { type: 'string', enum: ['pending', 'processing', 'completed', 'failed'] },
      },
    },
  },
  {
    id: 'message',
    name: 'Message',
    description: 'Message from Slack/Teams',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        messageId: { type: 'string' },
        threadId: { type: 'string' },
        parentMessageId: { type: 'string' },
        integrationSource: { type: 'string', enum: ['slack', 'teams', 'discord'] },
        externalId: { type: 'string' },
        channelId: { type: 'string' },
        channelName: { type: 'string' },
        channelType: { type: 'string', enum: ['dm', 'group_dm', 'public_channel', 'private_channel'] },
        workspaceId: { type: 'string' },
        workspaceName: { type: 'string' },
        from: { type: 'object' },
        text: { type: 'string' },
        formattedText: { type: 'string' },
        mentions: { type: 'array' },
        mentionedChannels: { type: 'array', items: { type: 'string' } },
        reactions: { type: 'array' },
        hasAttachments: { type: 'boolean' },
        attachments: { type: 'array' },
        isEdited: { type: 'boolean' },
        editedAt: { type: 'string', format: 'date-time' },
        isDeleted: { type: 'boolean' },
        deletedAt: { type: 'string', format: 'date-time' },
        isPinned: { type: 'boolean' },
        threadReplyCount: { type: 'number' },
        sentiment: { type: 'object' },
        topics: { type: 'array', items: { type: 'string' } },
        containsPII: { type: 'boolean' },
        messageType: { type: 'string', enum: ['question', 'announcement', 'discussion', 'decision', 'action_item'] },
        importance: { type: 'string', enum: ['low', 'normal', 'high'] },
        linkedOpportunityIds: { type: 'array', items: { type: 'string' } },
        linkedAccountIds: { type: 'array', items: { type: 'string' } },
        linkedContactIds: { type: 'array', items: { type: 'string' } },
        autoLinkingConfidence: { type: 'object' },
        sentAt: { type: 'string', format: 'date-time' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
        syncStatus: { type: 'string', enum: ['synced', 'pending', 'error'] },
        processingStatus: { type: 'string', enum: ['pending', 'processing', 'completed', 'failed'] },
      },
    },
  },
  {
    id: 'meeting',
    name: 'Meeting',
    description: 'Meeting recording and transcript from Zoom, Teams, Google Meet, Gong',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        meetingId: { type: 'string' },
        title: { type: 'string' },
        description: { type: 'string' },
        integrationSource: { type: 'string', enum: ['zoom', 'teams', 'google_meet', 'gong', 'chorus'] },
        externalId: { type: 'string' },
        externalUrl: { type: 'string' },
        startTime: { type: 'string', format: 'date-time' },
        endTime: { type: 'string', format: 'date-time' },
        duration: { type: 'number' },
        timezone: { type: 'string' },
        organizer: { type: 'object' },
        participants: { type: 'array' },
        participantCount: { type: 'number' },
        internalParticipantCount: { type: 'number' },
        externalParticipantCount: { type: 'number' },
        hasRecording: { type: 'boolean' },
        recordingUrl: { type: 'string' },
        recordingBlobUrl: { type: 'string' },
        recordingDuration: { type: 'number' },
        recordingSize: { type: 'number' },
        hasTranscript: { type: 'boolean' },
        transcriptUrl: { type: 'string' },
        transcriptBlobUrl: { type: 'string' },
        fullTranscript: { type: 'string' },
        transcriptSegments: { type: 'array' },
        meetingType: { type: 'string', enum: ['discovery', 'demo', 'negotiation', 'follow_up', 'closing', 'internal'] },
        topics: { type: 'array', items: { type: 'string' } },
        keyMoments: { type: 'array' },
        actionItems: { type: 'array' },
        objections: { type: 'array' },
        commitments: { type: 'array' },
        engagementMetrics: { type: 'object' },
        linkedOpportunityIds: { type: 'array', items: { type: 'string' } },
        linkedAccountIds: { type: 'array', items: { type: 'string' } },
        linkedContactIds: { type: 'array', items: { type: 'string' } },
        autoLinkingConfidence: { type: 'object' },
        createdAt: { type: 'string', format: 'date-time' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
        syncStatus: { type: 'string', enum: ['synced', 'pending', 'error'] },
        processingStatus: { type: 'string', enum: ['pending', 'processing', 'completed', 'failed'] },
      },
    },
  },
  {
    id: 'calendarevent',
    name: 'CalendarEvent',
    description: 'Calendar event from integrations (Google Calendar, Outlook)',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        eventId: { type: 'string' },
        title: { type: 'string' },
        description: { type: 'string' },
        integrationSource: { type: 'string', enum: ['google_calendar', 'outlook', 'exchange'] },
        externalId: { type: 'string' },
        externalUrl: { type: 'string' },
        startTime: { type: 'string', format: 'date-time' },
        endTime: { type: 'string', format: 'date-time' },
        duration: { type: 'number' },
        timezone: { type: 'string' },
        isAllDay: { type: 'boolean' },
        recurrence: { type: 'object' },
        location: { type: 'string' },
        locationType: { type: 'string', enum: ['in_person', 'online', 'phone'] },
        meetingUrl: { type: 'string' },
        organizer: { type: 'object' },
        attendees: { type: 'array' },
        attendeeCount: { type: 'number' },
        meetingShardId: { type: 'string' },
        linkedOpportunityIds: { type: 'array', items: { type: 'string' } },
        linkedAccountIds: { type: 'array', items: { type: 'string' } },
        linkedContactIds: { type: 'array', items: { type: 'string' } },
        createdAt: { type: 'string', format: 'date-time' },
        lastSyncedAt: { type: 'string', format: 'date-time' },
        syncStatus: { type: 'string', enum: ['synced', 'pending', 'error'] },
      },
    },
  },
  {
    id: 'activity',
    name: 'Activity',
    description: 'Unified activity tracking across all interaction types',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        activityType: {
          type: 'string',
          enum: ['email', 'meeting', 'call', 'message', 'document_view', 'document_share', 'other'],
        },
        activitySubtype: { type: 'string' },
        sourceShardId: { type: 'string' },
        sourceShardType: { type: 'string' },
        integrationSource: { type: 'string' },
        primaryParticipant: { type: 'object' },
        secondaryParticipants: { type: 'array' },
        subject: { type: 'string' },
        description: { type: 'string' },
        duration: { type: 'number' },
        outcome: { type: 'string' },
        notes: { type: 'string' },
        direction: { type: 'string', enum: ['inbound', 'outbound'] },
        context: { type: 'string' },
        linkedOpportunityIds: { type: 'array', items: { type: 'string' } },
        linkedAccountIds: { type: 'array', items: { type: 'string' } },
        linkedContactIds: { type: 'array', items: { type: 'string' } },
        activityDate: { type: 'string', format: 'date-time' },
        completionStatus: { type: 'string', enum: ['completed', 'scheduled', 'cancelled'] },
        importance: { type: 'string', enum: ['low', 'normal', 'high'] },
        engagementScore: { type: 'number', minimum: 0, maximum: 100 },
        sentiment: { type: 'number', minimum: -1, maximum: 1 },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'activityType', 'sourceShardId', 'sourceShardType', 'primaryParticipant', 'activityDate', 'completionStatus'],
    },
  },
  {
    id: 'interaction',
    name: 'Interaction',
    description: 'Track interactions between people for relationship graph',
    schemaVersion: '1.0',
    isSystem: false,
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        fromContactId: { type: 'string' },
        toContactIds: { type: 'array', items: { type: 'string' } },
        interactionType: { type: 'string', enum: ['email', 'meeting', 'call', 'message'] },
        sourceActivityId: { type: 'string' },
        interactionDate: { type: 'string', format: 'date-time' },
        frequency: { type: 'number' },
        recency: { type: 'number' },
        strength: { type: 'number', minimum: 0, maximum: 100 },
        sentiment: { type: 'number', minimum: -1, maximum: 1 },
        linkedOpportunityIds: { type: 'array', items: { type: 'string' } },
        linkedAccountIds: { type: 'array', items: { type: 'string' } },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', 'fromContactId', 'toContactIds', 'interactionType', 'sourceActivityId', 'interactionDate'],
    },
  },
];
